### ISSUE TITLE
Default City, Timezone and Date

### ISSUE THREAD

**Issue by jieyouxu** [UCLCSSA/User-Specification#1]
The current user specification allows the user to choose the default city, timezone and date, with the timezone defaulting to "UTC+0".

However, I don't think this is quite suitable:
- UK has Daylight Saving Time adjustments, meaning that the UK may be in "UTC+0" or "UTC+1" at different parts of the year.
- I recommend that the timezone, city and date be that of the actual location of the university (UCL in this case).

Requesting ideas from other members.

**Comment by FYHu** [comment]
Good idea i agreed with you, need another person to approve this idea and we can change the spec

**Comment by magetron** [comment]
Yes I do agree with the proposal.

**Comment by magetron** [comment]
We may close the issue since an obvious agreement has reached.
