### ISSUE TITLE
LaTex src upload

### ISSUE THREAD

**Issue by magetron** [UCLCSSA/User-Specification#2]
Suggest version control (git) to be applied on the original tex file instead of the current .pdf file.

S.t. an upload of the original tex file is recommended.

**Comment by magetron** [comment]
Is this written on overleaf? We can use the overleaf paid plan to sync with GitHub repositories.

**Comment by henryzt** [comment]
I guess this is probably a word theme so it's written in word

**Comment by magetron** [comment]
fair enough, therefore the original document (.docx) shall be version-controlled.

**Comment by henryzt** [comment]
Overleaf will be a great choice, or we can even use markdown?

**Comment by magetron** [comment]
Yes, exactly. A specification will not need these fancy themes. I believe a simple GitHub-styled markdown would suffice.

**Comment by jieyouxu** [comment]
I agree with the markdown usage, as LaTeX is primarily used for typesetting. In this case markdown should be sufficient since it's only notes and as long as they are legible, there's no need for LaTeX. Marking this issue as resolved.
