### ISSUE TITLE
Section 2.4.4 - User may choose the library

### ISSUE THREAD

**Issue by magetron** [UCLCSSA/User-Specification#7]
@FYHu  Please detail your issues here. Thanks for clarification.

**Comment by FYHu** [comment]
User may choose their favourite library to be displayed inside this block.

**Comment by FYHu** [comment]
I just want to ask whether you agree with adding this functionality or not.

**Comment by magetron** [comment]
Sure. It's just not clear if the library is "a favourite library functionality" .

Refer to #4, agreed to add such functionality.

Closing.
